name: Test

on:
  push:
    branches: ["main", "dev"]
  pull_request:
    branches: ["main", "dev"]

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Install Ubuntu Dependencies
        # We have to fix the source list for libwebkit2gtk-4.0-dev
        run: |
          sudo sh -c "echo jammy >> /etc/apt/sources.list.d/ubuntu.sources" &&
          sudo sh -c "echo jammy-security >> /etc/apt/sources.list.d/ubuntu.sources" &&
          sudo apt update &&
          sudo apt install libwebkit2gtk-4.0-dev \
              build-essential \
              curl \
              wget \
              libssl-dev \
              libgtk-3-dev \
              libayatana-appindicator3-dev \
              librsvg2-dev
      - name: Run tests
        run: cargo test --workspace --verbose
